### PR TITLE
fix: columns image load error breaks layout

### LINKED ISSUE #108: Errored images break card & columns layout
- [ ] cards should load properly even on image loading error

### PR DESCRIPTION
**Pull request by dicagno**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #108 

How-to test/reproduce:
- from web inspector, set image src to an invalid image url or `about:error`

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://feat-cols-image-load-error--danaher-ls-aem--hlxsites.hlx.page/

### CODE REVIEW

File: blocks/columns/columns.js [hunk 1]
```diff
@@ -2,9 +2,19 @@ export default function decorate(block) {
...
   block.classList.add(`columns-${cols.length}-cols`);
 
+  const imageAspectRatio = 1.7778;
+
   // setup image columns
   [...block.children].forEach((row) => {
     [...row.children].forEach((col) => {
+      const img = col.querySelector('img');
+      if (img) {
+        img.onerror = function () {
```
Comment (duynguyen) [inline blocks/columns/columns.js:12]: I think using `=>` will fix this warning

**Review by duynguyen — APPROVED** [review]
LGTM. minor: let clear the warning if that's an easy fix.

File: blocks/columns/columns.js (hunk 1 above)
Comment (dicagno) [reply blocks/columns/columns.js:13]: we need the `function` notation rather than the `=>` one in order to get proper scoping and the this object defined.
gonna fix this warning by ignoring func-names rule for this line
