### PR TITLE
633 Converter fix on feature section card

### LINKED ISSUE #633: Converter Fix on Feature Section Card

### PR DESCRIPTION
**Pull request by rgravitvl**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #633 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://633-fix-on-feature-section-card--danaher-ls-aem--hlxsites.hlx.page/

### CODE REVIEW

**Review by sharanagoudapatil — APPROVED** [review]

**Review by mhaack — APPROVED** [review]

File: tools/importer/transformers/util.js [hunk 1]
```diff
@@ -258,15 +260,14 @@ export const render = {
...
+    const featureImageEl = item.querySelector('div.featureimage');
     if (featureImageEl) {
       row.push(featureImageEl);
     }
   },
 
   text: (item, row) => {
-    const text = item.content.querySelector('div.text');
-    if (text) row.push(text);
+    if (item) row.push(item);
```
Comment (duynguyen) [inline tools/importer/transformers/util.js:270]: does this mean it will also include the `<div class="text">...</div>` in the new markup. do we want that?

Comment (rgravitvl) [reply tools/importer/transformers/util.js:270]: this was included the original code as well

**Review by duynguyen — APPROVED** [review]
