### PR TITLE
691 product product tile fixes

### LINKED ISSUE #691: [Product] Product tile fixes in the product family pages
- Remove gap between the product tiles
- Add margin between the results and pagination
- Fix the typo label 'Show Produt Details'
- Fix the bundle products list gray background 
- Fix the alignment of 'Show Product Details' link

### PR DESCRIPTION
**Pull request by deepakk799**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #691 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/m80-routine-stereo-microscopes
- After: https://691-product-product-tile-fixes--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/m80-routine-stereo-microscopes

### CODE REVIEW

**Comment by davenichols-DHLS** [comment]
Looks good to me.  The CLS is OK on this, but I noticed that as the title header changes the CLS is impacted on Desktop:  https://pagespeed.web.dev/analysis/https-691-product-product-tile-fixes--danaher-ls-aem--hlxsites-hlx-page-us-en-products-family-m80-routine-stereo-microscopes/paomj3uki0?form_factor=desktop

**Review by rgravitvl — APPROVED** [review]

File: blocks/product-children/product-children.js [hunk 1]
```diff
@@ -18,7 +18,10 @@ const childProducts = `
                 flex-direction:column;
             }
             atomic-result-list::part(result-list) {
-                gap: 0.5rem;
+                gap: 0.0rem;
```
Comment (duynguyen) [inline blocks/product-children/product-children.js:21]: isn't it equivalent to `gap: 0;` ?

**Review by duynguyen — APPROVED** [review]
LGTM. just left a minor comment about CSS styling
