### PR TITLE
fix: footer sizing

### LINKED ISSUE #55: Footer is too large
Compare screenshots ...

Screenshot 2023-09-12 at 11 54 28

### PR DESCRIPTION
**Pull request by dicagno**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #55 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://fix-footer-sizing--danaher-ls-aem--hlxsites.hlx.page/

### CODE REVIEW

**Comment by mhaack** [comment]
Can you make it little smaller. The height of the footer is still bigger then original.

**Review by duynguyen — APPROVED** [review]

**Review by mhaack — APPROVED** [review]

**Review by davenichols-DHLS — APPROVED** [review]
Looks great, thank you.

File: blocks/footer/footer.js [hunk 1]
```diff
@@ -19,6 +19,9 @@ export default async function decorate(block) {
     const footer = document.createElement('div');
     footer.innerHTML = html;
 
+    const a = footer.querySelector('ul>li:nth-child(3)>a'); // "Manage Cookies" link, third item of the first div
+    a.classList.add('ot-sdk-show-settings');
```
Comment (mhaack) [inline blocks/footer/footer.js:23]: Should we many detect this by the link text or href = "#" instead of the position. The links might get re-arranged and this will break.

**Review by mhaack — CHANGES_REQUESTED** [review]

File: blocks/footer/footer.js (hunk 1 above)
Comment (dicagno) [reply blocks/footer/footer.js:23]: I would prefer link href rather than text.
I agree on using the href. BTW can we use a more specific hash like #manage-cookies?

Comment (dicagno) [reply blocks/footer/footer.js:23]: yet another solution might be preserving this class in the conversion process.

Comment (mhaack) [reply blocks/footer/footer.js:23]: That would be better. But not sure if it still works.

@bpauli can we, for the footer, detected the hash link and if it has the special class `ot-sdk-show-settings` we rewrite it and add the class name as hash value?

Comment (dicagno) [reply blocks/footer/footer.js:23]: Hi @mhaack we have already applied a similar solution using the hash, and then restoring the href="#" back during the rendering process.

Comment (mhaack) [reply blocks/footer/footer.js]: Yep saw @bpauli 's PR

**Review by mhaack — APPROVED** [review]
