### PR TITLE
860 [Solutions] Products list missing analytics

### LINKED ISSUE #860: [Solutions] Product List missing analytics
Analytics are missing.
Wrong Query pipeline is being called.

### PR DESCRIPTION
**Pull request by sharanagoudapatil**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #860 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/
- After: https://860-prod-list-missing-analytics--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/products

### CODE REVIEW

File: scripts/commerce.js [hunk 1]
```diff
@@ -175,3 +195,83 @@ export async function getProductsOnSolutionsResponse() {
...
   }
 }
+
+function getCoveoAnalyticsPayload(duration, searchUid, response) {
+  const isInternal = typeof getCookie('exclude-from-analytics') !== 'undefined';
+  const clientId = getCookie('coveo_visitorId');
+  const results = [];
+  Array.from(response).forEach((res) => {
+    results.push({
+      documentUri: res.raw.uri,
```
Comment (davidzochowski) [inline scripts/commerce.js:205]: This should be res.uri, not res.raw.uri

File: scripts/commerce.js [hunk 2]
```diff
@@ -175,3 +195,83 @@ export async function getProductsOnSolutionsResponse() {
...
+      documentUriHash: res.raw.urihash,
+    });
+  });
+  const payload = {
+    actionCause: 'interfaceLoad',
+    anonymous: false,
+    clientId,
```
Comment (davidzochowski) [inline scripts/commerce.js:212]: This value is showing as null when I test on .hlx.page

File: scripts/commerce.js [hunk 3]
```diff
@@ -175,3 +195,83 @@ export async function getProductsOnSolutionsResponse() {
...
+    customData: {
+      context_workflow: getWorkflowFamily(),
+      context_host: window.DanaherConfig.host,
+      context_internal: isInternal,
+    },
+    language: 'en',
+    numberOfResults: response.length,
```
Comment (davidzochowski) [inline scripts/commerce.js:219]: This should be the total number of results, not just the number shown. For the test page in the PR, that would be the 'totalCount' value from the query response.

File: scripts/commerce.js [hunk 4]
```diff
@@ -124,35 +124,55 @@ function getWorkflowFamily() {
   return '';
 }
 
+function getProductsOnSolutionsApiPayload(qParam) {
```
Comment (davidzochowski) [inline scripts/commerce.js:127]: The payload for the Search Query needs to be updated. Do you want to do this in this branch or add as a new branch?

File: blocks/product-card/product-card.js [hunk 5]
```diff
@@ -1,20 +1,54 @@
...
     });
     block.innerHTML = '';
     block.append(cardList);
+    const ulEl = block.querySelector('ul');
+    ulEl.querySelectorAll('li').forEach((item) => {
+      item.querySelector('a').addEventListener('click', (e) => {
+        e.preventDefault();
+        const clickUri = item.querySelector('a').href;
+        const idx = item.querySelector('a').getAttribute('index');
+        onClickCoveoAnalyticsResponse(clickUri.split('/').pop(), idx);
```
Comment (davidzochowski) [inline blocks/product-card/product-card.js:49]: Im getting a NS_BINDING_ABORTED response when making the click event. This is because the page redirect is happening before the analytics event has finished sending to Coveo. Would you be able to delay the page redirect until you get a response from this analytics call?

**Review by davidzochowski — CHANGES_REQUESTED** [review]
Added comments

File: scripts/commerce.js (hunk 2 above)
Comment (sharanagoudapatil) [reply scripts/commerce.js:212]: Hi @mhaack - I'm facing this issue when we run this test page - https://860-prod-list-missing-analytics--danaher-ls-aem--hlxsites.hlx.page/us/en/solutions/mabs/cell-line-development/products but working fine on http://localhost:3000/us/en/solutions/mabs/cell-line-development/products. Any idea on this?

File: scripts/commerce.js (hunk 1 above)
Comment (sharanagoudapatil) [reply scripts/commerce.js]: updated with the changes.

File: scripts/commerce.js (hunk 3 above)
Comment (sharanagoudapatil) [reply scripts/commerce.js]: updated with the changes.

File: blocks/product-card/product-card.js (hunk 5 above)
Comment (sharanagoudapatil) [reply blocks/product-card/product-card.js:49]: I've added the 3ms delay. will test it with this change.

File: scripts/commerce.js [hunk 6]
```diff
@@ -167,7 +167,7 @@ export async function getProductsOnSolutionsResponse() {
 
     if (fullResponse && fullResponse.results.length > 0) {
       localStorage.setItem('solutions-product-list', JSON.stringify(fullResponse));
-      await makeCoveoAnalyticsApiRequest('/rest/v15/analytics/search', 'categoryProductKey', getCoveoAnalyticsPayload(fullResponse.duration, fullResponse.searchUid, fullResponse.results));
+      await makeCoveoAnalyticsApiRequest('/rest/v15/analytics/search', 'categoryProductKey', getCoveoAnalyticsPayload(fullResponse.duration, fullResponse.searchUid, fullResponse));
```
Comment (davidzochowski) [inline scripts/commerce.js:170]: Since the fullResponse object is being passed in, there's no need to have three separate parameters that all use the same object, let's just have the one parameter and get the values within the cooresponding method

Comment (sharanagoudapatil) [reply scripts/commerce.js]: Done.

**Review by davidzochowski — APPROVED** [review]

File: scripts/commerce.js (hunk 4 above)
Comment (sharanagoudapatil) [reply scripts/commerce.js:127]: As discussed, will add these changes as a separate task/branch. Thanks.

File: scripts/commerce.js (hunk 2 above)
Comment (sharanagoudapatil) [reply scripts/commerce.js]: Added the condition to check clientId to update the payload.
