### PR TITLE
Fix Updated product 404 page

### LINKED ISSUE #811: Fix: Update product 404 page

### PR DESCRIPTION
**Pull request by rgravitvl**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #811 

Test URLs:
- Before: https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica1
- After: https://fix-product-not-found-404--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/mica1

### CODE REVIEW

File: scripts/commerce.js [hunk 1]
```diff
@@ -94,8 +95,25 @@ export async function getProductResponse() {
       localStorage.setItem('product-details', JSON.stringify(fullResponse.results));
       return response;
     }
-    localStorage.removeItem('product-details');
-    window.location.replace('/us/en/products/product-not-found');
+
+    if (!response) {
+      localStorage.removeItem('product-details');
+      await fetch('/us/en/products/productNotFound.html')
```
Comment (mhaack) [inline scripts/commerce.js:101]: We should fetch /404.html here.

Comment (rgravitvl) [reply scripts/commerce.js]: Done

**Review by mhaack — APPROVED** [review]

**Review by davenichols-DHLS — APPROVED** [review]
Looks good, if @mhaack  is happy with this.
